"""Add user_api_keys table

Revision ID: a6364ba4b378
Revises: 001
Create Date: 2025-12-20 21:40:04.209897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6364ba4b378'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.create_index(op.f('ix_deployments_channel_type'), 'deployments', ['channel_type'], unique=False)
    op.alter_column('encrypted_credentials', 'oauth_token_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_encrypted_credentials_token_expiry'), 'encrypted_credentials', ['token_expiry'], unique=False)
    op.alter_column('execution_traces', 'message_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_execution_traces_created_at'), table_name='execution_traces')
    op.drop_index(op.f('ix_integrations_platform_id'), table_name='integrations')
    op.create_index(op.f('ix_integrations_type'), 'integrations', ['type'], unique=False)
    op.add_column('tools', sa.Column('tool_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tools_is_enabled'), 'tools', ['is_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_is_enabled'), table_name='tools')
    op.drop_column('tools', 'tool_type')
    op.drop_index(op.f('ix_integrations_type'), table_name='integrations')
    op.create_index(op.f('ix_integrations_platform_id'), 'integrations', ['platform_id'], unique=False)
    op.create_index(op.f('ix_execution_traces_created_at'), 'execution_traces', ['created_at'], unique=False)
    op.alter_column('execution_traces', 'message_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_encrypted_credentials_token_expiry'), table_name='encrypted_credentials')
    op.alter_column('encrypted_credentials', 'oauth_token_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index(op.f('ix_deployments_channel_type'), table_name='deployments')
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    # ### end Alembic commands ###
